name: Setup Pandoc Document Converter
description: Set up Pandoc.
author: Sia Codelabs

branding:
  icon: play-circle
  color: gray-dark

inputs:
  xelatex:
    description: Set if to install XeLaTeX.
    default: "false"

runs:
  using: composite
  steps:
    - name: Install Pandoc
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y pandoc

    - name: Install XeLaTeX if required
      if: inputs.xelatex
      shell: bash
      run: |
        sudo apt install -y texlive-xetex
