name: CI

on:
  push:
    branches:
      - "**"

permissions:
  contents: write

env:
  os: ubuntu-latest

jobs:
  test:
    runs-on: ${{ env.os }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      
      - name: Set up Pandoc
        uses: ./

      - name: Check installation
        run: pandoc --version
