name: Example

on: workflow_dispatch

permissions:
  contents: write

jobs:
  call:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Pandoc
        uses: siacodelabs/setup-pandoc@v1
      
      - name: Check installation
        run: pandoc --version
